// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rubrica.Infrastructure.Data;

#nullable disable

namespace Rubrica.Infrastructure.Migrations
{
    [DbContext(typeof(RubricaDbContext))]
    [Migration("20250622100858_AddCityWithSeedData")]
    partial class AddCityWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rubrica.Domain.Class.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Milano"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Roma"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Napoli"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Torino"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Firenze"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Venezia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bologna"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Genova"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Palermo"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bari"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Parigi"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Londra"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Barcellona"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Berlino"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Vienna"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Zurigo"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Stoccolma"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Copenhagen"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Oslo"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Helsinki"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Dublino"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Lisbona"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Atene"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Praga"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Budapest"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Varsavia"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Mosca"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Pechino"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Shanghai"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Seoul"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Mumbai"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Nuova Delhi"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Bangkok"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Melbourne"
                        },
                        new
                        {
                            Id = 41,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Chicago"
                        },
                        new
                        {
                            Id = 44,
                            Name = "San Francisco"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Vancouver"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Città del Messico"
                        },
                        new
                        {
                            Id = 48,
                            Name = "San Paolo"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Il Cairo"
                        });
                });

            modelBuilder.Entity("Rubrica.Domain.Class.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("Name", "Surname")
                        .IsUnique();

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Rubrica.Domain.Class.Contact", b =>
                {
                    b.HasOne("Rubrica.Domain.Class.City", null)
                        .WithMany()
                        .HasForeignKey("City")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
